apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-service
          image: rachstufff/soa-main:v1
          env:
            - name: JWT_SECRET
              value: "rahasia"
            - name: MYSQL_HOST
              value: "mysql-db"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "db_logistik"
            - name: RABBITMQ_HOST
              value: "rabbitmq-server"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: GOOGLE_CALLBACK_URL
              value: "http://localhost:30000/auth/google/callback"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: FRONTEND_URL
              value: "http://localhost:30080"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: main-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
